version: "3"

services:
  flarum:
    image: mondedie/flarum:stable
    container_name: flarum
    env_file:
      - C:\Users\46937\Documents\workspace\flarum\flarum.env
    volumes:
    #   
    #   
      - C:\Users\46937\Documents\workspace\flarum\flarum\storage/logs:/flarum/app/storage/logs
      - C:\Users\46937\Documents\workspace\flarum\flarum:/flarum/app
      - C:\Users\46937\Documents\workspace\flarum\flarum/extensions:/flarum/app/extensions
      - C:\Users\46937\Documents\workspace\flarum\flarum\public/assets:/flarum/app/public/assets
      - C:\Users\46937\Documents\workspace\flarum/nginx:/etc/nginx/flarum
    ports:
      - 8888:8888
    expose:
      - 3306
    # depends_on:
    #   - mariadb

  # mariadb:
  #   image: mariadb:10.5
  #   ports:
  #     - 3306:3306
  #   container_name: mariadb
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=123456
  #     - MYSQL_DATABASE=flarum
  #     - MYSQL_USER=flarum
  #     - MYSQL_PASSWORD=123456
  #   volumes:
  #     - C:\Users\46937\Documents\workspace\flarum\db:/var/lib/mysql